### ISSUE TITLE
Not available on NPM

### ISSUE THREAD

**Issue by BahKoo** [Breeze/breeze.bridge2.angular#1]
This package doesn't seem to be available on npm. Has it been published yet?

**Comment by marcelgood** [comment]
No, it hasn't been pushed yet. Still making some tweaks and haven't settled on the name yet. Should be out in the next few days.

**Comment by BahKoo** [comment]
Great, thanks!

**Comment by marcelgood** [comment]
The package has been pushed now.

https://www.npmjs.com/package/breeze-bridge2-angular
