### ISSUE TITLE
adapterCtor is not a constructor

### ISSUE THREAD

**Issue by dsoltesz** [Breeze/breeze.bridge2.angular#13]
I've been using breeze and the angular bride for quite some time but after upgrading to angular 8.2.7 and TS 3.5.3  I am now getting a error on launch with the registering of my ajax module.

the JS error is 

> 
> :64580/polyfills.js:12109 Unhandled Promise rejection: adapterCtor is not a constructor ; Zone: <root> ; Task: Promise.then ; Value: TypeError: adapterCtor is not a constructor
>     at Object.__config.registerAdapter (:64580/vendor.js:143129)
>     at new BreezeBridgeModule (:64580/main.js:12577)
>     at _createClass (:64580/vendor.js:85871)
>     at _createProviderInstance (:64580/vendor.js:85836)
>     at initNgModule (:64580/vendor.js:85742)
>     at new NgModuleRef_ (:64580/vendor.js:86852)
>     at createNgModuleRef (:64580/vendor.js:86835)

I haven't changes the code of how I register the adapter

```
import { AjaxHttpClientAdapter, BreezeBridgeHttpClientModule } from 'breeze-bridge2-angular';

const breezeClient = require('breeze-client');
require('breeze-client-labs/breeze.ajaxpost');

@NgModule({
  declarations: [],
  imports: [HttpClientModule],
  providers: [],
})
export class BreezeBridgeModule {
  constructor(private http: HttpClient) {
    breezeClient.config.registerAdapter('ajax', () => new AjaxHttpClientAdapter(this.http));
    const ajax = breezeClient.config.initializeAdapterInstance('ajax', AjaxHttpClientAdapter.adapterName, true);
    breezeClient.ajaxpost(ajax); // now we can use POST
  }
}
```

**Comment by steveschmitt** [comment]
Yes, things have changed with Angular 8.  

Now you will need to use the `breeze-client@next` version from npm (currently it's 2.0.0-alpha.16).  

And you will need to change the way you use `breeze.bridge2.angular`.  You _no longer_ import the `BreezeBridgeHttpClientModule` (because you get the error above).  Now you manually have to register the adapters, like this:
```
export class AppModule {
  constructor(http: HttpClient) {
    // Configure Breeze adapters
    ModelLibraryBackingStoreAdapter.register();
    UriBuilderJsonAdapter.register();
    config.registerAdapter('ajax', function() { return new AjaxHttpClientAdapter(http); } as any);
    config.initializeAdapterInstance('ajax', AjaxHttpClientAdapter.adapterName, true);
    DataServiceWebApiAdapter.register();
    NamingConvention.camelCase.setAsDefault();
    config.initializeAdapterInstance('uriBuilder', 'json');
  }
}
```
Yes, that's a lot of lines of registration code.  We will try to improve that in a future version of breeze.bridge2.angular.

This [configuration is demonstrated](https://github.com/Breeze/northwind-core-ng-demo/blob/master/STEPS.md#configure-app-module) in this [Northwind example project](https://github.com/Breeze/northwind-core-ng-demo) which you can try out if you happen to be using .NET Core.

**Comment by dsoltesz** [comment]
i ran ng update breeze-client@next --force  which installed the 2.0.0-alpha.16

 "breeze-bridge2-angular": "1.1.0",
    "breeze-client": "2.0.0-alpha.16",
    "breeze-client-labs": "1.5.12",

but its not finding these modules

`import { DataServiceWebApiAdapter } from 'breeze-client/adapter-data-service-webapi';
import { ModelLibraryBackingStoreAdapter } from 'breeze-client/adapter-model-library-backing-store';
import { UriBuilderJsonAdapter } from 'breeze-client/adapter-uri-builder-json';`

Also, a lot of exported types seem to be missing now

import * as breeze from 'breeze-client';
 breeze.DataServiceOptions;
breeze.EntityManagerOptions
breeze.QueryContext
breeze.MetadataStoreOptions

this is causing error in my TS for my metadata service and my entity manager service

also with the new configuration, how do you register the breeze.ajaxpost now as well

**Comment by steveschmitt** [comment]
Some of the "...Option" types have been renamed to "...Config"

I don't know why your imports are not found.

**Comment by dsoltesz** [comment]
i completely blew away node_modules and ran npm install..its still not finding those modules...however, i am able to build, just VS 2019 is giving me red squiggly that it can't find the modules.

import { config, NamingConvention, breeze } from 'breeze-client';

const ajax = config.initializeAdapterInstance('ajax', AjaxHttpClientAdapter.adapterName, true);

for the ajaxpost is just did this as the last line in the constructor

(breeze as any).ajaxpost(ajax);

but this doesn't seem to work as my post methods are going up as query string params and i'm getting a query string is too long response error.

**Comment by steveschmitt** [comment]
Hmm, I'll have to look into what's wrong with ajaxpost

**Comment by dsoltesz** [comment]
Any update with the ajaxpost not working correctly?

**Comment by steveschmitt** [comment]
Try `breeze-client@2.0.0-alpha.17`.  

The UriBuilderJsonAdapter was putting the parameters on the URL, even though they get encoded in the POST payload.  Fixed in 2.0.0-alpha.17.

Also, I've added the AjaxPostAdapter as part of the `breeze-client` npm package, so now you don't have to install it separately.  Instead you can:
```
import { AjaxPostAdapter } from 'breeze-client/adapter-ajax-post';
...
const ajax = config.initializeAdapterInstance('ajax', AjaxHttpClientAdapter.adapterName, true);
AjaxPostAdapter.wrapAjax(ajax as AjaxAdapter);
...
```

**Comment by dsoltesz** [comment]
this seems to be all working, please post any updates as they are made.  seems like we could just pass a flag into the initialiazeAdpaterInstance to configure ajax post for you instead of having to add that extra line yourself.

thanks for you help in time in getting this resolved so quickly.

**Comment by steveschmitt** [comment]
Excellent!  Happy to help.  I'll close this issue now.

You are right that we need to make the configuration easier.
