### ISSUE TITLE
Ivy compatibility angular/core@17

### ISSUE THREAD

**Issue by tesmat** [Breeze/breeze.bridge2.angular#14]
### I use breeze in my .NETCore SPA setup with Angular 17

When i added the breeze-bridge2-angular to my AppModule i get the following:

![image](https://github.com/Breeze/breeze.bridge2.angular/assets/18333229/12153543-a4e6-42e2-8e84-183abccd76c2)

### Maybe i'm missing something obvious...

I know the repo was not updated for the last 6/7 years, though it would be awesome to see this release.

### Thanks in advance!

**Comment by steveschmitt** [comment]
You should be using the [breeze-client](https://www.npmjs.com/package/breeze-client) package and set up Angular as shown in the [northwind-demo](https://github.com/Breeze/northwind-demo/blob/master/client/northwind-angular/src/app/app.module.ts) app.  You do not need breeze.bridge2.angular; it's included in breeze-client.  Start-from-scratch [instructions are here](https://github.com/Breeze/northwind-demo/blob/master/client/STEPS-Client-Angular.md).  Yes, the Northwind demo is old, but the basics are still relevant.

For Ivy, you should `npm install breeze-client@mjs`.  The `mjs` version is compatible with newer Angular versions.

**Comment by tesmat** [comment]
Wow thank you so much.
I knew i was missing something.
