### ISSUE TITLE
cannot pass parameter to registerFactory in TypeScript 

### ISSUE THREAD

**Issue by graphicsxp** [Breeze/breeze.bridge2.angular#3]
In my JavaScript project the following code worked, but not in TypeScript. This is because the validator takes a parameter : 

    Validator.registerFactory(this.greaterThanValidator, 'greaterThanValidator');

The correct syntax would be : 

   Validator.registerFactory((options) => this.greaterThanValidator(options), 'greaterThanValidator');

However the signature of registerFactory does not allow that.  How can I register this validator in TypeScript ? 

    public greaterThanValidator(options): Validator {
        const name = 'greaterThanValidator';
        const ctx = {
            val: options.value,
            messageTemplate: '"%displayName%" must be a greater than of %val%'
        };

        const validator = new Validator(name, _valFunction, ctx);

        function _valFunction(value, context) {
            if (value === null) {
                return true;
            }
            if (typeof (value) !== 'number') {
                return false;
            }
            if (context.min !== null && value <= context.val) {
                return false;
            }
            return true;
        }
        return validator;
    }

**Comment by lnu** [comment]
fixed 6 days agao https://github.com/Breeze/breeze.js/commit/b121abb655165a4adec70b2afa712ab591a5964a

**Comment by graphicsxp** [comment]
It was fixed indeed. Upgraded to latest version and it's working.
