### ISSUE TITLE
Validator.required() signature mismatch in d.ts

### ISSUE THREAD

**Issue by AbakumovAlexandr** [Breeze/breeze.bridge2.angular#6]
According to docs [here](http://breeze.github.io/doc-js/api-docs/classes/Validator.html), `Validator.required()` accepts a `context` parameter which should be an `Object` with an optional `bool` property `allowEmptyStrings`.

However in `d.ts` file its signature looks like:
`        static required(context?: { messageTemplate?: string }): Validator;`

**Comment by marcelgood** [comment]
Wrong repository, but fixed now.

**Comment by AbakumovAlexandr** [comment]
Thanks @marcelgood!
1. Will this fix be available in the next version of `breeze-bridge2-angular` package?
2. What is the correct repository for reporting `d.ts` issues?

**Comment by marcelgood** [comment]
1. Yes
2. https://github.com/Breeze/breeze.js
