### ISSUE TITLE
No getProperty() and setProperty() methods on Entity interface definition

### ISSUE THREAD

**Issue by AbakumovAlexandr** [Breeze/breeze.bridge2.angular#8]
According to [docs](http://breeze.github.io/doc-js/inside-entity.html), an entity has `getProperty()` and `setProperty()` methods. But TS type definition doesn't have those:
```
    export interface Entity {
        entityAspect: EntityAspect;
        entityType: EntityType;
    }
```

**Comment by marcelgood** [comment]
We appreciate the feedback, but please post these in the proper repository. This is the repo for the Breeze Angular bridge. Having said, that I've already fixed the type definitions to add the missing getProperty/setProperty methods.
