### ISSUE TITLE
Support for POST queries

### ISSUE THREAD

**Issue by TylerOrtiz** [Breeze/breeze.bridge2.angular#9]
I'm working on upgrading an existing application and am running into an issue where we were building our queries up using the .withParameters extension to be able to specify a POST. 

It seems the new bridge does not support a POST; or it may be that I am not using it properly. 

Ex.
` 
var baseQuery = EntityQuery
                .from("search/")
                .withParameters({
                    $method: "POST",
                    $encoding: "JSON",
                    $data: filters
                })
                .where(queryPredicate)
                .inlineCount()
                .using(this.breezeManager);

baseQuery.execute().then(()=> {})
`

**Comment by marcelgood** [comment]
The POST is independent of the bridge. POST support is provided by breeze.ajaxpost from breeze.js.labs, so I'm assuming that's what you are using. Breeze does not support POST queries out of the box. 

You have to reinitialize breeze.ajaxpost in your app module constructor, because the bridge swaps out the ajax adapter with its own, so breeze.ajaxpost needs to hook itself into the new ajax adapter. From your app module constructor call `breeze.config.ajaxpost()` without any parameters. This will install the POST capability into the correct ajax adapter.

**Comment by TylerOrtiz** [comment]
Thank you for your feedback.

Yes I am using the breeze.js.labs for this functionality and I tried at various points calling this method, including within my "CoreModule" constructor: `breeze.config.ajaxpost()` , but I can't seem to get an instance of breeze loaded from within TS/WebPack as there is no instance of `breeze` available.

I've tried getting an instance of the configuration as such:
`import { config  } from 'breeze-client';` 

And subsequently invoking the method:
`config.ajaxpost();` inside the constructor. But the `ajaxpost` method was never added to it, resulting in an undefined exception.

Should I move this discussion over to the https://github.com/Breeze/breeze.js.labs repository?

**Comment by marcelgood** [comment]
How are you importing breeze.ajaxpost? You should install the `breeze-client-labs` package with npm and then import `breeze-client-labs/breeze.ajaxpost`. The following helper function should do the trick. In this case it explicitly gets a hold of the ajax adapter and passes it to `config.ajaxpost`. 

```
import { config } from 'breeze-client'
import 'breeze-client-labs/breeze.ajaxpost';

export function configureAjaxPost() {
    let ajaxAdapter = config.getAdapterInstance('ajax');
    config.ajaxpost(ajaxAdapter);
}
```

Alternatively, here's a TypeScript rewrite of ajaxpost. You can add this to your project and then just import the configureAjaxPost function and call it from your app module ctor.

```
/*
 *  Functions to enable Breeze to use POST for queries when
 *  special parameters are passed using the .withParameters function.
 *
 * Copyright 2015 IdeaBlade, Inc.  All Rights Reserved.
 * Use, reproduction, distribution, and modification of this code is subject to the terms and
 * conditions of the IdeaBlade Breeze license, available at http://www.breezejs.com/license
 *
 * Special parameters:
 *  $method: ‘POST’ or ‘GET’ (the default)
 *  $encoding: ‘JSON’ or x-www-form-urlencoded (the default)
 *  $data: contains the data to be sent to the server
 *
 * Example:
 *   var query = breeze.EntityQuery.from('SimilarCustomersPOST')
 *            .withParameters({
 *                $method: 'POST',
 *                $encoding: 'JSON',
 *               $data: { CompanyName: 'Hilo Hattie', ContactName: 'Donald', City: 'Duck', Country: 'USA', Phone: '808-234-5678' }
 *           });
 *
 */

import { config } from 'breeze-client';

export function configureAjaxPost(ajaxAdapter?: any) {
    wrapAjaxImpl(ajaxAdapter);
}

function wrapAjaxImpl(ajaxAdapter: any) {
    if (!ajaxAdapter) {
        ajaxAdapter = config.getAdapterInstance('ajax');
    }
    if (ajaxAdapter.ajaxPostEnabled) {
        return; // already wrapped it.
    }

    const ajaxFunction = ajaxAdapter.ajax;
    if (ajaxFunction) {
        ajaxAdapter.ajax = function(settings: any) {
            processSettings(settings);
            return ajaxFunction.call(ajaxAdapter, settings);
        };
        ajaxAdapter.ajaxPostEnabled = true;
    }
}

// Handle the POST-specific properties in the settings - $method, $data, $encoding
function processSettings(settings: any) {
    const parameters = settings && settings.params;
    if (!parameters) { return settings; }

    // wrapped data; handle the special properties
    settings.type = parameters.$method || settings.type; // GET is default method

    const data = parameters.$data;
    if (data) {
        // if $data exists, assume all of other parameters are guidance for building a POST
        if (parameters.$encoding === 'JSON') {
            // JSON encoding
            settings.processData = false; // don't let JQuery form-encode it
            settings.contentType = 'application/json; charset=UTF-8';

            if (typeof (data) === 'object') {
                settings.data = JSON.stringify(data); // encode parameters as JSON
            } else {
                settings.data = data;
            }
        } else {
            settings.data = data;
        }
        // must be null or jQuery ajax adapter won't see settings.data
        settings.params = null;
    }

    return settings;
}

```

**Comment by TylerOrtiz** [comment]
So here is how I was doing it:
```
import * as ajaxpost from 'breeze-client-labs/breeze.ajaxpost';
import { config }  from `'breeze-client';
...
config.ajaxpost(); // in module constructor
```
Which results in:
```breeze_client__WEBPACK_IMPORTED_MODULE_8__.config.ajaxpost is not a function```

With your recommendation, it now works perfectly:
```
import { config }  from 'breeze-client';
import 'breeze-client-labs/breeze.ajaxpost';
...
config.ajaxpost(); // in module constructor
```

Thank you!

**Comment by marcelgood** [comment]
I see. Yeah, you can't do it that way. Because your code isn't actually using the ajaxpost import, TypeScript/Webpack will optimize the module away and so it doesn't get loaded at runtime. `import 'path_to_module'` is an ES6 import that forces the module to be loaded regardless. Technically, breeze.ajaxpost doesn't have any exports of its own. It's an augmentation module.

**Comment by marcelgood** [comment]
The corresponding d.ts just augments the breeze-client.config namespace.

```
import { config } from '../breeze-client';

declare module '../breeze-client' {
    namespace config {
        export function ajaxpost(ajaxAdapter?: Object): void;
    }
}
```
